language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t ygy0803/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true ygy0803/react-test-app npm test

after_success:
  - docker build -t ygy0803/docker-frontend ./frontend
  - docker build -t ygy0803/docker-backend ./backend
  - docker build -t ygy0803/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push ygy0803/docker-frontend
  - docker push ygy0803/docker-backend
  - docker push ygy0803/docker-nginx

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-fullstack-app"
  env: "Dockerfullsatckapp-env"
  bucket_name: 	elasticbeanstalk-us-east-1-635450248604
  bucket_path: "docker-fullstack-app"
  on:
    branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY